# Generated by Django 2.2.4 on 2019-08-05 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('number_of_questions', models.IntegerField()),
                ('pass_sacor', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
