# Generated by Django 2.2.4 on 2019-08-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='pass_sacor',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
