# Generated by Django 2.2.4 on 2019-08-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_page', '0005_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
    ]
