# Generated by Django 2.2.4 on 2019-08-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_page', '0006_remove_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
