# Generated by Django 2.2.4 on 2019-08-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_page', '0007_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.CharField(max_length=50),
        ),
    ]
